### ISSUE TITLE
SPI mode question

### ISSUE THREAD

**Issue by GeoIH** [mcauser/micropython-74hc595#1]
Hi @mcauser, why in the sr_74hc595_spi.py library don't use the SRCLK PIN.?
thanks for your help.

**Comment by mcauser** [comment]
Hi @GeoIH 
It does use the SRCLK pin, but not manually flipping it as with the bit bang version. The SPI interface handles it for you.

SRCLK is using the SPI SCK pin (IO18).
It's not referenced anywhere in the code other than `spi = SPI(1, 100000)`

The SPI pins for this ESP32 board (TinyPICO) are `23=MOSI`, `19=MISO`, `18=SCK`, `5=SS`.
MISO is not used and SS is used as a regular GPIO.

The SPI driver is using:
IO23 = SER
IO18 = SRCLK
IO5 = RCLK
IO32 = SRCLR
IO33 = OE

**Comment by GeoIH** [comment]
ok. I got it. thanks for your help.
